/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2021-07-03 06:07:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.board.reviewboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.semi4.vo.Like;
import com.semi4.dao.LikeDao;
import com.semi4.vo.Comment;
import com.semi4.dao.CommentDao;
import com.semi4.vo.ReviewBoard;
import com.semi4.dao.ReviewBoardDao;
import com.semi4.utils.StringUtils;
import com.semi4.vo.Admin;
import com.semi4.vo.QnaAnswer;
import java.util.List;
import com.semi4.dao.QnaAnswerDao;
import com.semi4.dao.UserDao;
import com.semi4.utils.NumberUtils;
import com.semi4.vo.QnaBoard;
import com.semi4.dao.QnaBoardDao;
import com.semi4.dao.GameDao;
import com.semi4.vo.Game;
import java.util.List;
import java.util.HashMap;
import java.util.Map;
import com.semi4.utils.StringUtils;
import com.semi4.vo.Admin;
import com.semi4.vo.User;

public final class reviewboarddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/board/reviewboard/../../common/footer.jsp", Long.valueOf(1625290619673L));
    _jspx_dependants.put("/board/reviewboard/../../common/navbar.jsp", Long.valueOf(1576223718000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.semi4.vo.QnaAnswer");
    _jspx_imports_classes.add("com.semi4.utils.NumberUtils");
    _jspx_imports_classes.add("com.semi4.dao.QnaBoardDao");
    _jspx_imports_classes.add("com.semi4.dao.LikeDao");
    _jspx_imports_classes.add("com.semi4.dao.UserDao");
    _jspx_imports_classes.add("com.semi4.vo.Game");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.semi4.vo.Like");
    _jspx_imports_classes.add("com.semi4.dao.ReviewBoardDao");
    _jspx_imports_classes.add("com.semi4.vo.ReviewBoard");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.semi4.dao.QnaAnswerDao");
    _jspx_imports_classes.add("com.semi4.vo.User");
    _jspx_imports_classes.add("com.semi4.vo.QnaBoard");
    _jspx_imports_classes.add("com.semi4.dao.GameDao");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("com.semi4.dao.CommentDao");
    _jspx_imports_classes.add("com.semi4.vo.Comment");
    _jspx_imports_classes.add("com.semi4.utils.StringUtils");
    _jspx_imports_classes.add("com.semi4.vo.Admin");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<title>리뷰 게시글 상세 정보</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   // 세션 객체에서 LOGINED_USER로 저장된 사용자객체를 조회
   request.setCharacterEncoding("utf-8");
   User loginedUser = (User) session.getAttribute("LOGINED_USER");
   Admin loginedAdmin = (Admin) session.getAttribute("LOGINED_ADMIN");

      out.write("     \r\n");
      out.write("<nav style=\"background-color: #000000;\">\r\n");
      out.write("     <div class=\"container\" style=\"padding-bottom: 10px;\">\r\n");
      out.write("       <div class=\"navbar-header\" style=\"padding-top: 20px;\">\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"/semi-4/home.jsp\" style=\"font-size:30px; color: #ffffff;\">JHTA Games</a>\r\n");
      out.write("          \r\n");
      out.write("          ");
 	
          	String bigKeyword = StringUtils.nullToBlank(request.getParameter("bigkeyword"));
          	       	
          
      out.write(" \r\n");
      out.write("          <form class=\"navbar-form navbar-left\" id=\"bigkeyword-form\" method=\"get\" action=\"/semi-4/purchase/searchform.jsp\">\r\n");
      out.write("             <div class=\"form-group\">\r\n");
      out.write("                <input type=\"text\" name=\"bigkeyword\" id=\"keyword-search\" class=\"form-control\" placeholder=\"Search\" style=\"width: 475px;\" value=\"");
      out.print(bigKeyword );
      out.write("\">\r\n");
      out.write("                <button class=\"btn btn-default\" type=\"button\" onclick=\"bigSearch()\">\r\n");
      out.write("                    <i class=\"glyphicon glyphicon-search\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("             </div>\r\n");
      out.write("          </form>\r\n");
      out.write("      \r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       ");

         if(loginedUser != null) {
            if(loginedAdmin != null) {
       
      out.write("\r\n");
      out.write("           <ul class=\"nav navbar-nav navbar-right\" style=\"padding-top:20px;\">\r\n");
      out.write("                <li style=\"font-size: 18px;\"><a href=\"/semi-4/logout.jsp\" style=\"color: #ffffff; background-color: #000000;\"><span class=\"glyphicon glyphicon-log-out\"></span> 로그아웃</a></li>\r\n");
      out.write("                <li style=\"font-size: 18px;\"><a href=\"/semi-4/admin/adminMain.jsp\" style=\"color: #ffffff; background-color: #000000;\"><span class=\"glyphicon glyphicon-eye-open\"></span> 관리자페이지</a></li>\r\n");
      out.write("             </ul> \r\n");
      out.write("       ");

            } else {
       
      out.write("\r\n");
      out.write("\t       <ul class=\"nav navbar-nav navbar-right\" style=\"padding-top:20px;\">\r\n");
      out.write("\t          <li style=\"font-size: 18px;\"><a href=\"/semi-4/logout.jsp\" style=\"color: #ffffff; background-color: #000000;\"><span class=\"glyphicon glyphicon-log-out\" style=\"color: #ffffff;\"></span> 로그아웃</a></li>\r\n");
      out.write("\t          <li style=\"font-size: 18px;\"><a href=\"/semi-4/user/userinfoform.jsp\" style=\"color: #ffffff; background-color: #000000;\"><span class=\"glyphicon glyphicon-user\"></span> 마이페이지</a></li>\r\n");
      out.write("\t          <li>\r\n");
      out.write("\t\t          <a href=\"/semi-4/purchase/cart.jsp\" style=\"padding:0px; margin-top:10px; background-color: #000000;\">\r\n");
      out.write("\t\t          <button type=\"button\" class=\"btn btn-default btn-sm glyphicon glyphicon-shopping-cart default\" style=\"font-size: 14px;\">\r\n");
      out.write("\t\t          </button>\r\n");
      out.write("\t\t          </a>\r\n");
      out.write("\t          </li>\r\n");
      out.write("\t       </ul>\r\n");
      out.write("\r\n");
      out.write("      ");

      
            }
        }
      
      out.write("\r\n");
      out.write("       \r\n");
      out.write("       ");

         if(loginedUser == null) {
      
      out.write("\r\n");
      out.write("       <div class=\"nav navbar-nav navbar-right\" style=\"padding-top:30px;\">\r\n");
      out.write("          <a href=\"/semi-4/loginform.jsp\" style=\"padding:0px;\"><button type=\"button\" class=\"btn btn-default btn\" style=\"font-size: 16px;\" >로그인</button></a>\r\n");
      out.write("          <a href=\"/semi-4/user/registerform.jsp\" style=\"padding:0px;\"><button type=\"button\" class=\"btn btn-default btn\" style=\"font-size: 16px;\">회원가입</button></a>\r\n");
      out.write("          <a href=\"/semi-4/loginform.jsp\" style=\"padding:0px; margin-top:10px\">\r\n");
      out.write("\t          <button type=\"button\" class=\"btn btn-default btn-sm glyphicon glyphicon-shopping-cart default\" \r\n");
      out.write("\t          \t\t\tonclick=\"clickcart()\" style=\"font-size: 16px; margin-bottom: 2px;\">\r\n");
      out.write("\t          </button>\r\n");
      out.write("          </a>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("      ");

         }
      
      out.write("    \r\n");
      out.write("     </div>\r\n");
      out.write("     <div class=\"row\" style=\"background-color: #ffffff;\">\r\n");
      out.write("     \r\n");
      out.write("        <div class=\"container\" style=\"padding: 10px;\">\r\n");
      out.write("             <ul class=\"nav navbar-nav\">\r\n");
      out.write("                <li class=\"active\" style=\"font-size: 20px;\"><a href=\"/semi-4/home.jsp\" style=\"background-color: #ffffff\" >홈</a></li>\r\n");
      out.write("                <li style=\"font-size: 20px;\"><a href=\"/semi-4/purchase/gamemenu.jsp\" style=\"background-color: #ffffff\">게임</a></li>\r\n");
      out.write("                <li class=\"dropdown\">\r\n");
      out.write("                   <a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"\" style=\"background-color: #ffffff; font-size: 20px;\">고객지원\r\n");
      out.write("                       <span class=\"caret\"></span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <ul class=\"dropdown-menu\">\r\n");
      out.write("                       <li style=\"font-size: 16px;\"><a href=\"/semi-4/board/noticeboard/noticeboard.jsp\">공지사항</a></li>\r\n");
      out.write("                       <li style=\"font-size: 16px;\"><a href=\"/semi-4/board/qnaboard/qnaboard.jsp\">QnA 게시판</a></li>\r\n");
      out.write("                       <li style=\"font-size: 16px;\"><a href=\"/semi-4/board/reviewboard/reviewboard.jsp\">리뷰 게시판</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li style=\"font-size: 20px;\"><a href=\"/semi-4/event/eventmain.jsp\" style=\"background-color: #ffffff\">이벤트</a></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("             \r\n");
      out.write("             <ul class=\"nav navbar-nav navbar-right\" >\r\n");
      out.write("                <li style=\"border:none;box-shadow:none\"><button type=\"button\" class=\"btn btn-default glyphicon glyphicon-thumbs-up\" onclick=\"clickFacebook()\" style=\"background:#4e69a2;color:#ffffff;border:none;margin-top:10px;margin-right:10px; font-size: 15px;\"><i class=\"fab fa-facebook\" style=\"background:#4e69a2;color:#ffffff;\"></i> 페이스북</button></li>\r\n");
      out.write("                <li style=\"border:none;box-shadow:none\"><button type=\"button\" class=\"btn btn-default glyphicon glyphicon-expand\" onclick=\"clickYoutube()\" style=\"background:#ff0000;color:#ffffff;border:none;margin-top:10px; font-size: 15px;\"><i class=\"fab fa-youtube-play\" style=\"background:#ff0000;color:#ffffff\"></i> 유튜브</button></li>\r\n");
      out.write("             </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function clickFacebook() {\r\n");
      out.write("      window.open(\"http://www.facebook.com/\");\r\n");
      out.write("   }\r\n");
      out.write("   function clickYoutube() {\r\n");
      out.write("      window.open(\"http://www.youtube.com/\");\r\n");
      out.write("   }\r\n");
      out.write("   function clickcart() {\r\n");
      out.write("      alert(\"로그인 후 이용하세요.\")\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function bigSearch() {\r\n");
      out.write("\t \r\n");
      out.write("\t   var bigkeyword = document.getElementById(\"keyword-search\").value;\r\n");
      out.write("\t  \r\n");
      out.write("\t   if (bigkeyword == \"\") {\r\n");
      out.write("\t\t   alert(\"검색어를 입력하세요.\")\r\n");
      out.write("\t\t   return;\r\n");
      out.write("\t   }\r\n");
      out.write("\t\r\n");
      out.write("\t   document.getElementById(\"bigkeyword-form\").submit();\r\n");
      out.write("   }\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div style=\"border-bottom: 1px solid grey;\">\r\n");
      out.write("\t\t\t<h2>리뷰 게시글 상세 정보</h2>\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t<table class=\"table\" style=\"border: 1px solid grey;\">\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t<col width=\"60%\">\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t");

					request.setCharacterEncoding("utf-8");

					String from = request.getParameter("from");
					int pageNo = Integer.parseInt(request.getParameter("pageno"));
					int reviewNo = Integer.parseInt(request.getParameter("reviewno"));
					ReviewBoardDao reviewboardDao = ReviewBoardDao.getInstance();
					ReviewBoard board = reviewboardDao.getReviewBoardByNo(reviewNo);
					
					int likeCount = board.getLikeCount();
					
					int count = board.getCount();
					count++;
					board.setCount(count);

					reviewboardDao.updatereviewcount(board);
				
      out.write("\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t<th>글번호</th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(board.getNo());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(board.getTitle());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t<th>글쓴이</th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(board.getUser().getName());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th style=\"vertical-align: top;\">본문</th>\r\n");
      out.write("\t\t\t\t\t\t<th><textarea class=\"col-12\" style=\"width: 100%; min-height : 300px;  resize: none; border: 0;\" readonly>");
      out.print(board.getContent());
      out.write("</textarea></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr class=\"active\">\r\n");
      out.write("\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(board.getCount());
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>좋아요</th>\r\n");
      out.write("\t\t\t\t\t\t<th>");
      out.print(board.getLikeCount() );
      out.write("</th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t");

						if (loginedUser != null && loginedUser.getNo().intValue() == board.getUser().getNo().intValue()) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\thref=\"reviewmodify.jsp?reviewno=");
      out.print(board.getNo());
      out.write("&pageno=");
      out.print(pageNo);
      out.write("&from=");
      out.print(from );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-warning\">수정</a> <a\r\n");
      out.write("\t\t\t\t\t\thref=\"reviewdeletereg.jsp?reviewno=");
      out.print(board.getNo());
      out.write("&pageno=");
      out.print(pageNo );
      out.write("&from=");
      out.print(from );
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn btn-danger\">삭제</a>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btn btn-warning disabled\">수정</a> <a href=\"\" class=\"btn btn-danger disabled\">삭제</a>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t");

							LikeDao likeDao = LikeDao.getInstance();
						
							if (loginedUser != null) {							
								Like setlike = new Like();
								ReviewBoard setboard = new ReviewBoard();
								setboard.setNo(reviewNo);
								setlike.setReviewBoard(setboard);
								setlike.setUser(loginedUser);
								int like = likeDao.getlikeByNoes(setlike);
								if (like == 0) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"reviewboardlikeup.jsp?reviewno=");
      out.print(reviewNo );
      out.write("&pageno=");
      out.print(pageNo );
      out.write("&from=");
      out.print(from );
      out.write("\" class=\"btn btn-default\"><span class=\"glyphicon glyphicon-thumbs-up\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t");

								} else if (like == 1) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"reviewboardlikedown.jsp?reviewno=");
      out.print(reviewNo );
      out.write("&pageno=");
      out.print(pageNo );
      out.write("&from=");
      out.print(from );
      out.write("\" class=\"btn btn-info\"><span class=\"glyphicon glyphicon-thumbs-up\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t");

								}
							} else {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<a href=\"\" class=\"btn btn-default disabled\"><span class=\"glyphicon glyphicon-thumbs-up\"></span></a>\r\n");
      out.write("\t\t\t\t\t\t");

							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t");

							if ("reviewboard.jsp".equals(from)) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"reviewboard.jsp?pageno=");
      out.print(pageNo);
      out.write("&from=");
      out.print(from );
      out.write(" %>\" class=\"btn btn-success\">목록</a>\r\n");
      out.write("\t\t\t\t\t\t");

							} else if("userreviewform.jsp".equals(from)) {
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../../user/userreviewform.jsp?\" class=\"btn btn-success\">돌아가기</a>\r\n");
      out.write("\t\t\t\t\t\t");

							} 
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-12\"\r\n");
      out.write("\t\t\t\tstyle=\"border-bottom: 1px dotted #999; padding-top: 10px;\">\r\n");
      out.write("\t\t\t\t");

					CommentDao commentDao = CommentDao.getInstance();
					List<Comment> comments = commentDao.getCommentByReviewNo(reviewNo);

					for (Comment comment : comments) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<strong>");
      out.print(comment.getUser().getName());
      out.write("</strong>\r\n");
      out.write("\t\t\t\t");
				
					
						if (loginedUser != null && loginedUser.getNo().intValue() == comment.getUser().getNo().intValue()) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<div id=\"first-box-");
      out.print(comment.getNo());
      out.write("\" class=\"pull-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-warning btn-xs\" onclick=\"goModify(");
      out.print(comment.getNo());
      out.write(")\">댓글수정</button>\r\n");
      out.write("\t\t\t\t\t<a href=\"commentdeletereg.jsp?commentno=");
      out.print(comment.getNo());
      out.write("&reviewno=");
      out.print(reviewNo );
      out.write("&pageno=");
      out.print(pageNo );
      out.write("&from=");
      out.print(from );
      out.write("\" class=\"btn btn-danger btn-xs\">댓글삭제</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-warning btn-xs disabled\">댓글수정</button>\r\n");
      out.write("\t\t\t\t\t<a href=\"\" class=\"btn btn-danger btn-xs disabled\">댓글삭제</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
					
					}
				
      out.write("\r\n");
      out.write("\t\t\t\t<p id=\"first-content-");
      out.print(comment.getNo());
      out.write('"');
      out.write('>');
      out.print(comment.getContent());
      out.write("</p>\r\n");
      out.write("\t\t\t\t<form id=\"second-form-");
      out.print(comment.getNo());
      out.write("\" method=\"post\" action=\"commentmodified.jsp\"\r\n");
      out.write("\t\t\t\t\tstyle=\"display: none; margin-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"commentno\" value=\"");
      out.print(comment.getNo());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"pageno\" value=\"");
      out.print(pageNo);
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"from\" value=\"");
      out.print(from);
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t<div id=\"second-box-");
      out.print(comment.getNo());
      out.write("\" class=\"pull-right\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-xs\" onclick=\"submitreply(");
      out.print(comment.getNo());
      out.write(")\">댓글 수정</button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-default btn-xs\" onclick=\"backreply(");
      out.print(comment.getNo());
      out.write(")\">취소</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"comment-content-");
      out.print(comment.getNo());
      out.write("\" class=\"form-control\" name=\"commentcontent\" style=\"margin-bottom: 10px;\">");
      out.print(comment.getContent() );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t");

			}

			if (loginedUser != null) {
		
      out.write("\r\n");
      out.write("\t\t<form id=\"comment-add\" action=\"commentaddreg.jsp\" class=\"well\" method=\"get\" action=\"commentadd.jsp\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"pageno\" value=\"");
      out.print(pageNo);
      out.write("\" /> \r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"reviewno\" value=\"");
      out.print(reviewNo);
      out.write("\" /> \r\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"from\" value=\"");
      out.print(from);
      out.write("\" /> \r\n");
      out.write("\t\t\t<label>댓글쓰기</label>\r\n");
      out.write("\t\t\t<textarea class=\"form-control\" id=\"addcomment-content\" name=\"commentcontent\" rows=\"3\"></textarea>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<button class=\"btn btn-info pull-right\" type=\"button\" onclick=\"addSubmit()\">등록</button>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer id=\"t3-footer\" class=\"wrap t3-footer\" style=\"height:120px;padding-top:0;padding-bottom:0; background-color: #000000; color: #ffffff; width:100%; bottom: 0;\">\r\n");
      out.write("<div class=\"container\" style=\"padding-top:0;padding-bottom:0\">\r\n");
      out.write("<div class=\"navbar-footer\">\r\n");
      out.write("   <ul class=\"nav nav-pills\" style=\"margin-top:10px; margin-left: auto; margin-right: auto; width: 50%;\">\r\n");
      out.write("      <li><a href=\"http://jhta.kr/page/academy.php?id=5\" target=\"_blank\">회사소개</a></li>\r\n");
      out.write("      <li><a href=\"http://jhta.kr/page/edu/intro.php?type=1\" target=\"_blank\">이용약관</a></li>\r\n");
      out.write("      <li><a href=\"http://jhta.kr/page.php?p=policy2\" target=\"_blank\">개인정보처리방침</a></li>\r\n");
      out.write("      <li><a href=\"http://jhta.kr/page/academy.php?id=9\" target=\"_blank\">찾아오시는길</a></li>\r\n");
      out.write("      <li><a href=\"http://jhta.kr/page/academy/history.php\" target=\"_blank\">HTA 연혁</a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<address style=\"padding-top:8px;padding-bottom:0\">\r\n");
      out.write("   <p styl=\"margin-bottom:0; text-align: center\">JHTA GAMES <span class=\"bars\">|</span> 소재지 : 서울특별시 종로구 봉익동 율곡로10길 105 디아망 빌딩 4층  (주)중앙HTA <span class=\"bars\">|</span> 대표이사 : 이준스쨔응 <span class=\"bars\">|</span> 개인정보관리책임자 : 인호쓰</p>\r\n");
      out.write("   <p style=\"margin-bottom:0; text-align: center\">사업자등록번호 : 010-1234-5678 <span class=\"bars\">|</span> 통신판매업신고 : 2019-중앙HTA-1905th <span class=\"bars\">|</span> 고객센터 : 010-1234-5678(대일쨩번호) <span class=\"bars\">|</span> 전자우편 : aslkd@gmail.com</p>\r\n");
      out.write("</address>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<section class=\"t3-copyright\" style=\"padding-top:0px;padding-bottom:0;margin-top:-8px; background-color: #000000; color: #ffffff;\">\r\n");
      out.write("<div class=\"container\" style=\"padding-top:0;padding-bottom:0\">\r\n");
      out.write("   <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-12 copyright\" style=\"text-align: center;\">\r\n");
      out.write("         <small>Copyright © JHTA GAMES. All Rights Reserved. </small>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\t\t\r\n");
      out.write("\t\tfunction countUp() {\r\n");
      out.write("\t\t\tvar likeup = document.getElementById(\"like-up\").value;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tlikeup +1;\r\n");
      out.write("\t\t\tdocument.getElementById(\"like-up\").value = likeup;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tdocument.getElementById(\"like-form\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction goModify(commentNo) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"first-box-\" + commentNo).style.display = \"none\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"first-content-\" + commentNo).style.display = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"second-form-\" + commentNo).style.display = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"second-box-\" + commentNo).style.display = \"\";\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction backreply(commentNo) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"first-box-\" + commentNo).style.display = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"first-content-\" + commentNo).style.display = \"\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"second-form-\" + commentNo).style.display = \"none\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"second-box-\" + commentNo).style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction submitreply(commentNo) {\r\n");
      out.write("\t\t\tvar content = document.getElementById(\"comment-content-\" + commentNo).value;\r\n");
      out.write("\t\t\tif (content == \"\") {\r\n");
      out.write("\t\t\t\talert(\"수정할 댓글을 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tdocument.getElementById(\"second-form-\" + commentNo).submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction addSubmit() {\r\n");
      out.write("\t\t\tvar addcontent = document.querySelector(\"#addcomment-content\").value;\r\n");
      out.write("\t\t\tif (addcontent == \"\") {\r\n");
      out.write("\t\t\t\talert(\"댓글을 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"comment-add\").submit();\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
